name: Azure Login and Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          # Replace with your tenant ID
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          # Replace with your client ID
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # Replace with your client secret
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          # Set environment to your Azure cloud
          environment: azurecloud

      - name: Set Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          cd backend/
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      - name: Archive files
        run: |
          cd backend/
          zip -r ../function.zip .
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          # Replace with your Azure Function App name
          app-name: ${{ secrets.AZURE_FUNCTION_NAME }}
          package: function.zip
          # Replace with your Azure Function App publish profile
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Clean up
        run: rm function.zip
